//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMassage_QA.Areas.Admin.Models.FW
{
    using System;
    using System.Collections.Generic;
    
    public partial class BDang_Ky
    {
        public int ID_dang_Ky { get; set; }
        public string Dangkycongty { get; set; }
        public string tencongtychuthuong { get; set; }
        public string Diachi { get; set; }
        public Nullable<int> TenGiamdocky { get; set; }
        public Nullable<int> Tenketoantruong { get; set; }
        public Nullable<int> Tenthuquy { get; set; }
        public Nullable<int> Thu_Kho { get; set; }
        public string Masothue { get; set; }
        public string Dienthoai { get; set; }
        public string Sotaikhoan { get; set; }
        public string Logo { get; set; }
        public string Tainganhang { get; set; }
        public string SoFax { get; set; }
        public Nullable<int> NamTaichinh { get; set; }
        public string Diachi_VanPhong { get; set; }
        public string Motanganhnghe { get; set; }
        public string TenTiengAnh { get; set; }
        public Nullable<int> Songaythuno { get; set; }
        public Nullable<System.DateTime> Ngayhoachtoan { get; set; }
        public Nullable<System.DateTime> Ngaykethuchoachtoan { get; set; }
        public Nullable<int> Muc_dong_BH { get; set; }
        public Nullable<int> Ngay_Cong { get; set; }
        public string Lam_CN { get; set; }
        public Nullable<System.TimeSpan> DK_Open { get; set; }
        public Nullable<System.TimeSpan> DK_Close { get; set; }
        public Nullable<int> Thoi_Gian_Check_Int { get; set; }
        public Nullable<int> Thoi_Gian_Ca { get; set; }
        public string Chu_y { get; set; }
        public string Thong_bao { get; set; }
        public string thank_custommer { get; set; }
        public Nullable<int> phuphi { get; set; }
        public Nullable<int> thuevat { get; set; }
        public string xacnhan { get; set; }
    }
}
