//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMassage_QA.Areas.Admin.Models.FW
{
    using System;
    using System.Collections.Generic;
    
    public partial class BLich_Su_Vao_Phan_Mem
    {
        public int ID { get; set; }
        public Nullable<int> Nhan_su_ID { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public Nullable<System.DateTime> Ngay_vao { get; set; }
    }
}
