//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMassage_QA.Areas.Admin.Models.FW
{
    using System;
    using System.Collections.Generic;
    
    public partial class BLog_Permission_BCacQuenCT
    {
        public int PermissionId { get; set; }
        public string PermissionName_TenQuyen { get; set; }
        public string Description { get; set; }
        public string BusinessId { get; set; }
        public Nullable<bool> Quyencapcao { get; set; }
    }
}
