//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMassage_QA.Areas.Admin.Models.FW
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discount_Code
    {
        public int Id { get; set; }
        public string Name_discount { get; set; }
        public string Sale_code { get; set; }
        public string Discount_code_view { get; set; }
        public Nullable<int> status { get; set; }
        public string Note { get; set; }
    }
}
