//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMassage_QA.Areas.Admin.Models.FW
{
    using System;
    using System.Collections.Generic;
    
    public partial class Footer_client
    {
        public int Id { get; set; }
        public string Name_f { get; set; }
        public string Diachi_f { get; set; }
        public string Sodienthoai { get; set; }
        public string F_Note { get; set; }
        public Nullable<int> F_Active { get; set; }
    }
}
