//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMassage_QA.Areas.Admin.Models.FW
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Data_MassageEntities7 : DbContext
    {
        public Data_MassageEntities7()
            : base("name=Data_MassageEntities7")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BDang_Ky> BDang_Ky { get; set; }
        public virtual DbSet<BLich_Su_Vao_Phan_Mem> BLich_Su_Vao_Phan_Mem { get; set; }
        public virtual DbSet<BLog_Business_TenQuyen> BLog_Business_TenQuyen { get; set; }
        public virtual DbSet<BLog_Permission_BCacQuenCT> BLog_Permission_BCacQuenCT { get; set; }
        public virtual DbSet<Discount_Code> Discount_Code { get; set; }
        public virtual DbSet<Footer_client> Footer_client { get; set; }
        public virtual DbSet<GrantPermission> GrantPermission { get; set; }
        public virtual DbSet<phieu_thu> phieu_thu { get; set; }
        public virtual DbSet<SettingAdmin> SettingAdmin { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbl_CaLamViec> tbl_CaLamViec { get; set; }
        public virtual DbSet<tbl_Loai_Ca_Lam_Viec> tbl_Loai_Ca_Lam_Viec { get; set; }
        public virtual DbSet<tbl_Phieu_Chi> tbl_Phieu_Chi { get; set; }
        public virtual DbSet<tbl_User> tbl_User { get; set; }
        public virtual DbSet<tblCategories> tblCategories { get; set; }
        public virtual DbSet<tblColecttion> tblColecttion { get; set; }
        public virtual DbSet<tblCheckin> tblCheckin { get; set; }
        public virtual DbSet<tblEmployees> tblEmployees { get; set; }
        public virtual DbSet<tblNotification> tblNotification { get; set; }
        public virtual DbSet<tblOrder> tblOrder { get; set; }
        public virtual DbSet<tblOrderDetail> tblOrderDetail { get; set; }
        public virtual DbSet<tblRegister> tblRegister { get; set; }
        public virtual DbSet<tblRoom> tblRoom { get; set; }
        public virtual DbSet<tblSepending> tblSepending { get; set; }
        public virtual DbSet<tblServicies> tblServicies { get; set; }
        public virtual DbSet<tblSlider> tblSlider { get; set; }
        public virtual DbSet<tblStaffInEmployee> tblStaffInEmployee { get; set; }
        public virtual DbSet<tblStarOrder> tblStarOrder { get; set; }
        public virtual DbSet<TypeEmployee> TypeEmployee { get; set; }
        public virtual DbSet<UserGroup> UserGroup { get; set; }
    
        public virtual ObjectResult<Bill_Result> Bill()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Bill_Result>("Bill");
        }
    
        public virtual ObjectResult<Bill_Chiitet_Result> Bill_Chiitet()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Bill_Chiitet_Result>("Bill_Chiitet");
        }
    
        public virtual ObjectResult<Close_shift_Result> Close_shift()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Close_shift_Result>("Close_shift");
        }
    
        public virtual ObjectResult<DOANH_THU_CA_Result> DOANH_THU_CA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DOANH_THU_CA_Result>("DOANH_THU_CA");
        }
    
        public virtual ObjectResult<DOANH_THU_NAM_Result> DOANH_THU_NAM()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DOANH_THU_NAM_Result>("DOANH_THU_NAM");
        }
    
        public virtual ObjectResult<DOANH_THU_NGAY_Result> DOANH_THU_NGAY()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DOANH_THU_NGAY_Result>("DOANH_THU_NGAY");
        }
    
        public virtual ObjectResult<Lay_Employee_Type_Result> Lay_Employee_Type()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Lay_Employee_Type_Result>("Lay_Employee_Type");
        }
    
        public virtual ObjectResult<Lay_rom_hoat_dong_Result> Lay_rom_hoat_dong()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Lay_rom_hoat_dong_Result>("Lay_rom_hoat_dong");
        }
    
        public virtual ObjectResult<LEPVC_Result> LEPVC()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LEPVC_Result>("LEPVC");
        }
    
        public virtual ObjectResult<map_employee_Result> map_employee()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<map_employee_Result>("map_employee");
        }
    
        public virtual ObjectResult<mediumStar_Result> mediumStar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<mediumStar_Result>("mediumStar");
        }
    
        public virtual ObjectResult<mediumStar12_Result> mediumStar12()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<mediumStar12_Result>("mediumStar12");
        }
    
        public virtual ObjectResult<NhatKy_Result> NhatKy()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NhatKy_Result>("NhatKy");
        }
    
        public virtual ObjectResult<NumberOfServings_Result> NumberOfServings()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NumberOfServings_Result>("NumberOfServings");
        }
    
        public virtual ObjectResult<Order_Admin_Categories_0_Result> Order_Admin_Categories_0()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Order_Admin_Categories_0_Result>("Order_Admin_Categories_0");
        }
    
        public virtual ObjectResult<Order_Admin_Employee_0_Result> Order_Admin_Employee_0()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Order_Admin_Employee_0_Result>("Order_Admin_Employee_0");
        }
    
        public virtual ObjectResult<Order_Admin_Service_0_Result> Order_Admin_Service_0()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Order_Admin_Service_0_Result>("Order_Admin_Service_0");
        }
    
        public virtual ObjectResult<RantingStarEmployee_Result> RantingStarEmployee()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RantingStarEmployee_Result>("RantingStarEmployee");
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_473aab5c_708a_415e_a0ca_637768959ba0()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_473aab5c_708a_415e_a0ca_637768959ba0");
        }
    
        public virtual ObjectResult<Staff_client_Result> Staff_client()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Staff_client_Result>("Staff_client");
        }
    }
}
