//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMassage_QA.Areas.Admin.Models.FW
{
    using System;
    using System.Collections.Generic;
    
    public partial class phieu_thu
    {
        public int Id { get; set; }
        public string nguoinoptien { get; set; }
        public string sodienthoai { get; set; }
        public string diachi { get; set; }
        public Nullable<double> sotien_thu { get; set; }
        public string noidungthu { get; set; }
        public string Note_thu { get; set; }
        public string nguoinop { get; set; }
        public string nguoilap { get; set; }
        public Nullable<System.DateTime> ngaylap { get; set; }
        public string sochungtu_thu { get; set; }
    }
}
