//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMassage_QA.Areas.Admin.Models.FW
{
    using System;
    using System.Collections.Generic;
    
    public partial class SettingAdmin
    {
        public int Id { get; set; }
        public Nullable<int> thoigian { get; set; }
        public Nullable<int> thoigianca { get; set; }
        public string fontchu { get; set; }
        public Nullable<int> cochu { get; set; }
        public string chuy { get; set; }
        public string mauonline { get; set; }
        public string maucokhach { get; set; }
        public string maucho { get; set; }
        public string thongbao { get; set; }
        public string maunhanvienonline { get; set; }
        public string maunhanviencokhach { get; set; }
        public string colorbar { get; set; }
        public Nullable<int> ID_User { get; set; }
        public string mauchu { get; set; }
        public Nullable<int> heightContent { get; set; }
        public Nullable<int> widthContent { get; set; }
        public Nullable<int> heightRight { get; set; }
        public Nullable<int> widthRight { get; set; }
        public Nullable<int> hienthichuthich { get; set; }
    }
}
