//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMassage_QA.Areas.Admin.Models.FW
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_User
    {
        public int Id_User { get; set; }
        public string Chucvu { get; set; }
        public string GroupID { get; set; }
        public string Name_User { get; set; }
        public string Email_User { get; set; }
        public string Pass_User { get; set; }
        public string Note { get; set; }
        public Nullable<bool> U_Status { get; set; }
        public Nullable<int> Dark_Light_theme { get; set; }
        public Nullable<int> Full_full_screen { get; set; }
    }
}
