//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMassage_QA.Areas.Admin.Models.FW
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CaLamViec
    {
        public int Id { get; set; }
        public Nullable<int> LoaiCaLamViecId { get; set; }
        public string NameEmployee { get; set; }
        public string FirtTime { get; set; }
        public string LastTime { get; set; }
        public string Note { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Id_giao { get; set; }
        public Nullable<int> Id_nhan { get; set; }
        public Nullable<decimal> Tong_tien_thu_trong_ca { get; set; }
        public Nullable<decimal> Tien_ca_truoc_ban_giao { get; set; }
        public Nullable<decimal> Tong_tien_mat { get; set; }
        public Nullable<decimal> Tong_tien_cuoi_ca { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string Note_shift { get; set; }
    
        public virtual tbl_Loai_Ca_Lam_Viec tbl_Loai_Ca_Lam_Viec { get; set; }
    }
}
