//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMassage_QA.Areas.Admin.Models.FW
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblColecttion
    {
        public int Id { get; set; }
        public Nullable<int> Order_Id { get; set; }
        public Nullable<System.DateTime> CL_NewDay { get; set; }
        public string CL_Number { get; set; }
        public Nullable<int> CL_NhanSuId { get; set; }
        public Nullable<bool> CL_Active { get; set; }
        public string CL_Content { get; set; }
        public string CL_Note { get; set; }
        public Nullable<double> CL_Money { get; set; }
    
        public virtual tblOrder tblOrder { get; set; }
    }
}
