//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMassage_QA.Areas.Admin.Models.FW
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEmployees()
        {
            this.tblRegister = new HashSet<tblRegister>();
            this.tblSepending = new HashSet<tblSepending>();
            this.tblStaffInEmployee = new HashSet<tblStaffInEmployee>();
        }
    
        public int Id { get; set; }
        public string E_Code { get; set; }
        public Nullable<int> TypeEmployeeId { get; set; }
        public string E_Name { get; set; }
        public string E_Phone { get; set; }
        public string E_CMND { get; set; }
        public string E_Address { get; set; }
        public Nullable<System.DateTime> E_Dayin { get; set; }
        public Nullable<System.DateTime> E_Dayout { get; set; }
        public string E_Note { get; set; }
        public string E_Image { get; set; }
        public Nullable<int> E_Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRegister> tblRegister { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSepending> tblSepending { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStaffInEmployee> tblStaffInEmployee { get; set; }
    }
}
