//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMassage_QA.Areas.Admin.Models.FW
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNotification
    {
        public int Id { get; set; }
        public string N_Content { get; set; }
        public Nullable<int> N_Show { get; set; }
        public string N_Note { get; set; }
    }
}
