//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMassage_QA.Areas.Admin.Models.FW
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblOrder()
        {
            this.tblColecttion = new HashSet<tblColecttion>();
            this.tblOrderDetail = new HashSet<tblOrderDetail>();
            this.tblStarOrder = new HashSet<tblStarOrder>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> FirtDayCheckin { get; set; }
        public string FirtHourCheckin { get; set; }
        public Nullable<System.DateTime> LastDayCheckin { get; set; }
        public string LastHourCheckin { get; set; }
        public string O_number { get; set; }
        public Nullable<int> NhanVienID { get; set; }
        public Nullable<System.DateTime> DayNew { get; set; }
        public string Note { get; set; }
        public Nullable<int> Chay { get; set; }
        public Nullable<int> Ca_lam_Id { get; set; }
        public Nullable<int> Id_Code_sale { get; set; }
        public Nullable<int> phantramgiam { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblColecttion> tblColecttion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrderDetail> tblOrderDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStarOrder> tblStarOrder { get; set; }
    }
}
