//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMassage_QA.Areas.Admin.Models.FW
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRegister
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public string UserName { get; set; }
        public string Pass { get; set; }
        public Nullable<bool> Active { get; set; }
        public string GroupBy { get; set; }
        public string Email { get; set; }
    
        public virtual tblEmployees tblEmployees { get; set; }
    }
}
