//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMassage_QA.Areas.Admin.Models.FW
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSepending
    {
        public int Id { get; set; }
        public Nullable<int> IdNhan { get; set; }
        public Nullable<System.DateTime> S_NewDay { get; set; }
        public string S_Number { get; set; }
        public Nullable<int> S_NhanSuId { get; set; }
        public Nullable<bool> S_Active { get; set; }
        public string S_Content { get; set; }
        public string S_Note { get; set; }
        public Nullable<double> S_Money { get; set; }
    
        public virtual tblEmployees tblEmployees { get; set; }
    }
}
