//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMassage_QA.Areas.Admin.Models.FW
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblServicies
    {
        public int Id { get; set; }
        public string S_Name { get; set; }
        public Nullable<bool> S_Active { get; set; }
        public string S_Note { get; set; }
        public Nullable<double> S_Money { get; set; }
    }
}
