//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMassage_QA.Areas.Admin.Models.FW
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStaffInEmployee
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<int> E_NumberStar_View1 { get; set; }
        public Nullable<int> E_NumberStar_Admin { get; set; }
        public string E_Image { get; set; }
        public string E_ImageList { get; set; }
        public string E_Details { get; set; }
        public Nullable<double> E_Money { get; set; }
        public Nullable<int> E_Status { get; set; }
    
        public virtual tblEmployees tblEmployees { get; set; }
    }
}
