//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMassage_QA.Areas.Admin.Models.FW
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeEmployee
    {
        public int Id { get; set; }
        public string TE_Name { get; set; }
        public Nullable<bool> TE_Active { get; set; }
        public string TE_Note { get; set; }
        public Nullable<int> TE_Admin_Staff { get; set; }
    }
}
